### ISSUE TITLE
Hello How i can run migration

### ISSUE THREAD

**Issue by arbims** [cnizzardini/cakephp-docker#15]
1/ I tried to do migration but I can't see the migration on my mysql database
2/ how I can change the default connection I want to use database.local.php

thank you

**Comment by cnizzardini** [comment]
1. I haven't tried running a migrations exactly in here, but I did in this https://github.com/mixerapi/demo#docker which is based off this template and it works.
2. I haven't tried this but maybe modify the docker-compose.yml: https://github.com/cnizzardini/cakephp-docker/blob/master/docker-compose.yml and the connection string here: https://github.com/cnizzardini/cakephp-docker/blob/master/.docker/php.env.development

Sidenote: what OS are you running? There are some MacOS compatibility issues (#13) that I have not had a chance to sit down and debug since I am generally on Linux.
